export const COUNTRIES = [
  { name: 'United States', code: 'US', currency: { code: 'USD', symbol: '$', name: 'US Dollar' } },
  { name: 'United Kingdom', code: 'GB', currency: { code: 'GBP', symbol: '£', name: 'British Pound' } },
  { name: 'European Union', code: 'EU', currency: { code: 'EUR', symbol: '€', name: 'Euro' } },
  { name: 'India', code: 'IN', currency: { code: 'INR', symbol: '₹', name: 'Indian Rupee' } },
  { name: 'Japan', code: 'JP', currency: { code: 'JPY', symbol: '¥', name: 'Japanese Yen' } },
  { name: 'Canada', code: 'CA', currency: { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar' } },
  { name: 'Australia', code: 'AU', currency: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' } },
  { name: 'Brazil', code: 'BR', currency: { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' } },
  { name: 'Nigeria', code: 'NG', currency: { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' } },
  { name: 'Singapore', code: 'SG', currency: { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' } },
  { name: 'South Korea', code: 'KR', currency: { code: 'KRW', symbol: '₩', name: 'South Korean Won' } },
  { name: 'China', code: 'CN', currency: { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' } },
  { name: 'Switzerland', code: 'CH', currency: { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' } },
  { name: 'Russia', code: 'RU', currency: { code: 'RUB', symbol: '₽', name: 'Russian Ruble' } },
  { name: 'Mexico', code: 'MX', currency: { code: 'MXN', symbol: 'MX$', name: 'Mexican Peso' } },
  { name: 'South Africa', code: 'ZA', currency: { code: 'ZAR', symbol: 'R', name: 'South African Rand' } },
  { name: 'United Arab Emirates', code: 'AE', currency: { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' } },
  { name: 'Turkey', code: 'TR', currency: { code: 'TRY', symbol: '₺', name: 'Turkish Lira' } },
  { name: 'Indonesia', code: 'ID', currency: { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' } },
  { name: 'Thailand', code: 'TH', currency: { code: 'THB', symbol: '฿', name: 'Thai Baht' } },
  { name: 'Vietnam', code: 'VN', currency: { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' } },
  { name: 'Philippines', code: 'PH', currency: { code: 'PHP', symbol: '₱', name: 'Philippine Peso' } },
  { name: 'Malaysia', code: 'MY', currency: { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' } },
  { name: 'New Zealand', code: 'NZ', currency: { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' } },
  { name: 'Hong Kong', code: 'HK', currency: { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' } },
];

export const LANGUAGES = [
  { name: 'English', code: 'en' },
  { name: 'Spanish', code: 'es' },
  { name: 'French', code: 'fr' },
  { name: 'German', code: 'de' },
  { name: 'Italian', code: 'it' },
  { name: 'Portuguese', code: 'pt' },
  { name: 'Japanese', code: 'ja' },
  { name: 'Chinese', code: 'zh' },
  { name: 'Arabic', code: 'ar' },
  { name: 'Russian', code: 'ru' },
  { name: 'Korean', code: 'ko' },
  { name: 'Dutch', code: 'nl' },
  { name: 'Hindi', code: 'hi' },
];
